name: HafalQ
description: "Application Quran For You."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  http: 0.13.6
  flutter:
    sdk: flutter
  audioplayers: 6.5.0
  provider: ^6.0.0
  shared_preferences: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  hijri: ^3.0.0
  animations: ^2.0.11
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # <-- dipindahkan ke sini

flutter_launcher_icons:  # <-- HARUS di luar dev_dependencies
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather.ttf
